- name: Deploy Nginx with Rollback
  block:
    - name: Backup Nginx index
      copy:
        src: /var/www/html/index.nginx-debian.html
        dest: /var/www/html/index.nginx-debian.html.bak
        remote_src: true
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
        cache_valid_time: 3000
      tags: [install,deploy]
    - name: Sample HTML template
      template:
        src: index.html.j2
        dest: /var/www/html/index.nginx-debian.html
        owner: www-data
        group: www-data
        mode: '0644'
      notify: nginx changed
      tags: [page,deploy]
    - name: Health check
      uri:
        url: http://{{ansible_host}}/
        status_code: 200
      tags: deploy
  rescue:
    - name: Rollback index
      copy:
        src: /var/www/html/index.nginx-debian.html.bak
        dest: /var/www/html/index.nginx-debian.html
        remote_src: true
      notify: nginx changed
