- name: Apply Nginx Action
  listen: nginx changed
  service:
    name: nginx
    state: "{{ nginx_service_action }}"
      # - name: Restart Nginx
  #  listen: nginx changed
    #  service:
    #    name: nginx
      #    state: restarted
