- name: Reload Nginx
  listen: nginx changed
  service:
    name: nginx
    state: reloaded
      #- name: Restart Nginx
  #  listen: nginx changed
    #  service:
    #    name: nginx
      #    state: restarted
