- name: Strict health check
  include_tasks: "checks_{{ strict_health_check | default(false) | ternary('strict','basic') }}.yml"
  tags: deploy
- name: Ensure db_password is defined
  assert:
    that:
      - db_password is defined
  when: "'prod' in group_names"
  tags: deploy
