- name: Deploy Nginx with Rollback
  block:
    - name: Backup Nginx index
      copy:
        src: /var/www/html/index.nginx-debian.html
        dest: /var/www/html/index.nginx-debian.html.bak
        remote_src: true
        owner: www-data
        group: www-data
        mode: "0644"
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true
        cache_valid_time: 3000
      tags: [install, deploy]
    - name: Install utilities
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - htop
        - net-tools
      when: item != 'htop' or 'dev' in group_names
    - name: Sample HTML template
      template:
        src: index.html.j2
        dest: /var/www/html/index.nginx-debian.html
        owner: www-data
        group: www-data
        mode: '0644'
      notify: nginx changed
      tags: [page, deploy]
    - name: Strict health check
      uri:
        url: http://{{ ansible_host }}/
        status_code: 200
      when: strict_health_check | default(false)
      tags: deploy
    - name: Ensure db_password is defined.
      assert:
        that:
          - db_password is defined
      when: "'prod' in group_names"
      tags: deploy
    - name: Create users
      user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
      loop:
        - { name: devuser, shell: /bin/bash, sudo: true }
        - { name: opsuser, shell: /bin/zsh, sudo: false }
    - name: Add sudo users
      copy:
        dest: /etc/sudoers.d/{{ item.name }}
        content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
        mode: "0440"
        validate: "visudo -cf %s"
      loop:
        - { name: devuser, shell: /bin/bash, sudo: true }
        - { name: opsuser, shell: /bin/zsh, sudo: false }
      when: item.sudo
  rescue:
    - name: Rollback index
      copy:
        src: /var/www/html/index.nginx-debian.html.bak
        dest: /var/www/html/index.nginx-debian.html
        remote_src: true
        owner: www-data
        group: www-data
        mode: "0644"
      notify: nginx changed
